name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.21
      env:
        CIBW_BUILD: cp312-* cp313-* cp314-*
        CIBW_ARCHS_LINUX: x86_64 aarch64
        CIBW_SKIP: "*-musllinux_*"
        CIBW_BEFORE_BUILD_LINUX: yum install -y gcc python3-devel || apt-get install -y gcc python3-dev

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}
        path: ./wheelhouse/*.whl

  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install build
      run: python -m pip install --upgrade pip build

    - name: Build sdist
      run: python -m build --sdist

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz

  publish:
    name: Publish to PyPI
    needs: [build-wheels, build-sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyusdt
    permissions:
      id-token: write

    steps:
    - name: Download all distributions
      uses: actions/download-artifact@v4
      with:
        pattern: "*"
        merge-multiple: true
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
