name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc python3-dev

    - name: Build extension
      run: make

    - name: Run tests (without bpftrace)
      run: |
        PYTHONPATH=. python tests/load.py
        PYTHONPATH=. python tests/test_missing.py

    - name: Install bpftrace for USDT tests
      run: |
        sudo apt-get install -y bpftrace
      continue-on-error: true

    - name: Run USDT tests (with bpftrace)
      run: |
        if command -v bpftrace &> /dev/null; then
          sudo PYTHONPATH=. python tests/probe.py
          sudo PYTHONPATH=. python tests/test_events.py
        else
          echo "bpftrace not available, skipping USDT tests"
        fi
      continue-on-error: true
